# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Ensure all files have `# frozen_string_literal: true` at the top
Style/FrozenStringLiteralComment:
  Enabled: true

# Enforce single quotes for strings
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

# Enforce consistent spacing around square brackets
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  Enabled: true