# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Ensure all files have `# frozen_string_literal: true` at the top
Style/FrozenStringLiteralComment:
  Enabled: true